import type { NextPage } from 'next';
import Head from 'next/head';
import { Container, Header } from '../components';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Odonto Market</title>
        <meta name="description" content={'Generated by create next app'} />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />
        <Container>
        </Container>
      </main>
    </div>
  )
}

export default Home;
